name: 'Generate Codecov coverage report'

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  coverage:

    runs-on: ubuntu-latest
    name: Create coverage report and upload results to Codecov on Ubuntu

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.5
      - name: Build with Maven
        run: mvn -V --color always -ntp clean verify
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: 'target/site/jacoco/jacoco.xml'
          token: ${{secrets.CODECOV_TOKEN}}
